In [3]:
import numpy as np

np.zeros(4)

array([0., 0., 0., 0.])

In [4]:
np.ones(4)

array([1., 1., 1., 1.])

In [6]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [9]:
lista1 = [1,2,3,4]
array1 = np.array(lista1)
array1

array([1, 2, 3, 4])

In [10]:
lista1

[1, 2, 3, 4]

In [12]:
lista1 = [1,2,3,4]
lista2 = [5,6,7,8]
lista_doble = (lista1,lista2)
lista_doble

([1, 2, 3, 4], [5, 6, 7, 8])

In [13]:
array_doble = np.array(lista_doble)
array_doble

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
array_doble.shape

(2, 4)

In [16]:
array_doble.dtype

dtype('int32')