In [1]:
import numpy as np

array1 = np.array([1,2,3,4])
array1

array([1, 2, 3, 4])

In [2]:
array1 + 4

array([5, 6, 7, 8])

In [3]:
lista1 = [1,2,3,4]
lista2 = [5,6,7,8]
lista_doble = (lista1,lista2)
array_doble = np.array(lista_doble)

In [4]:
array_doble

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
array_doble.dtype

dtype('int32')

In [6]:
array_doble.shape

(2, 4)

In [7]:
array_doble ** 2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]], dtype=int32)

In [8]:
array_doble - 4

array([[-3, -2, -1,  0],
       [ 1,  2,  3,  4]])