In [2]:
import pandas as pd
import numpy as np

array1 = np.arange(9).reshape(3,3)
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([array1,array1])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([array1,array1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
serie1 = pd.Series([1,2,3], index=['a','b','c'])
serie2 = pd.Series([4,5,6], index=['d','e','f'])

pd.concat([serie1,serie2])

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [6]:
serie1

a    1
b    2
c    3
dtype: int64

In [7]:
serie2

d    4
e    5
f    6
dtype: int64

In [8]:
pd.concat([serie1,serie2], keys=['serie1','serie2'])

serie1  a    1
        b    2
        c    3
serie2  d    4
        e    5
        f    6
dtype: int64

In [10]:
dataframe1 = pd.DataFrame(np.random.rand(3,3), columns=['a','b','c'])
dataframe1

a         b         c
0  0.707581  0.043904  0.757539
1  0.593439  0.881332  0.162486
2  0.165256  0.271918  0.666310

In [11]:
dataframe2 = pd.DataFrame(np.random.rand(2,3),columns=['a','b','c'])
dataframe2

a        b         c
0  0.517963  0.86722  0.387852
1  0.947076  0.38147  0.493810

In [12]:
pd.concat([dataframe1,dataframe2])

a         b         c
0  0.707581  0.043904  0.757539
1  0.593439  0.881332  0.162486
2  0.165256  0.271918  0.666310
0  0.517963  0.867220  0.387852
1  0.947076  0.381470  0.493810

In [13]:
pd.concat([dataframe1,dataframe2], ignore_index=True)

a         b         c
0  0.707581  0.043904  0.757539
1  0.593439  0.881332  0.162486
2  0.165256  0.271918  0.666310
3  0.517963  0.867220  0.387852
4  0.947076  0.381470  0.493810